from __future__ import annotations

import json
import re
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import tensorflow as tf
from flask import Flask, render_template, request

from ui_constraints import SEP, ensure_constraints


BASE_DIR = Path(__file__).resolve().parent
ARTIFACT_DIR = BASE_DIR / "csat_artifacts"

MODEL_PATH = ARTIFACT_DIR / "csat_ann.keras"
PREPROCESSOR_PATH = ARTIFACT_DIR / "preprocessor.pkl"
LABEL_ENCODER_PATH = ARTIFACT_DIR / "label_encoder.pkl"
FEATURE_CONFIG_PATH = ARTIFACT_DIR / "feature_config.json"
DECISION_CONFIG_PATH = ARTIFACT_DIR / "decision_config.json"
METRICS_PATH = BASE_DIR / "deployment_metrics.json"

app = Flask(__name__)


# -----------------------------------------------------------------------------
# Load trained model artifacts
# -----------------------------------------------------------------------------
REQUIRED_ARTIFACTS = [
    MODEL_PATH,
    PREPROCESSOR_PATH,
    LABEL_ENCODER_PATH,
    FEATURE_CONFIG_PATH,
    DECISION_CONFIG_PATH,
]

missing = [str(p) for p in REQUIRED_ARTIFACTS if not p.exists()]
if missing:
    raise FileNotFoundError(
        "Missing deployment artifacts:\n- "
        + "\n- ".join(missing)
        + "\n\nCopy the complete csat_artifacts folder generated by "
          "the successful notebook next to app.py."
    )

model = tf.keras.models.load_model(MODEL_PATH, compile=False)
preprocessor = joblib.load(PREPROCESSOR_PATH)
label_encoder = joblib.load(LABEL_ENCODER_PATH)

with FEATURE_CONFIG_PATH.open("r", encoding="utf-8") as f:
    feature_config = json.load(f)

with DECISION_CONFIG_PATH.open("r", encoding="utf-8") as f:
    decision_config = json.load(f)

with METRICS_PATH.open("r", encoding="utf-8") as f:
    deployment_metrics = json.load(f)

MODEL_FEATURES = feature_config["model_features"]
CATEGORICAL_FEATURES = feature_config["categorical_features"]
MODEL_NAME = feature_config.get(
    "selected_validation_candidate",
    deployment_metrics.get("selected_model", "ANN"),
)


# -----------------------------------------------------------------------------
# Training-valid UI constraints
# -----------------------------------------------------------------------------
UI_CONSTRAINTS, UI_CONSTRAINT_PATH = ensure_constraints(BASE_DIR)


# -----------------------------------------------------------------------------
# Feature engineering: same logic used by the final notebook
# -----------------------------------------------------------------------------
def parse_datetime_safe(series: pd.Series) -> pd.Series:
    try:
        return pd.to_datetime(series, errors="coerce", format="mixed")
    except TypeError:
        return pd.to_datetime(series, errors="coerce")


def safe_log1p(series: pd.Series) -> pd.Series:
    values = pd.to_numeric(series, errors="coerce")
    values = values.where(values >= 0)
    return np.log1p(values)


def build_features(frame: pd.DataFrame) -> pd.DataFrame:
    out = frame.copy()

    for col in ["item_price", "connected_handling_time"]:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")

    datetime_cols = [
        "order_date_time",
        "issue_reported_at",
        "issue_responded",
        "survey_response_date",
    ]
    for col in datetime_cols:
        if col in out.columns:
            out[col] = parse_datetime_safe(out[col])

    if {"issue_reported_at", "issue_responded"}.issubset(out.columns):
        response = (
            out["issue_responded"] - out["issue_reported_at"]
        ).dt.total_seconds() / 60
        out["response_time_minutes"] = response.where(response >= 0)

    if {"order_date_time", "issue_reported_at"}.issubset(out.columns):
        age = (
            out["issue_reported_at"] - out["order_date_time"]
        ).dt.total_seconds() / 3600
        out["order_to_issue_hours"] = age.where(age >= 0)

    if {"issue_responded", "survey_response_date"}.issubset(out.columns):
        delay = (
            out["survey_response_date"] - out["issue_responded"]
        ).dt.total_seconds() / 3600
        out["survey_delay_hours"] = delay.where(delay >= 0)

    if "issue_reported_at" in out.columns:
        hour = out["issue_reported_at"].dt.hour
        out["issue_hour"] = hour
        out["issue_day_name"] = out["issue_reported_at"].dt.day_name()
        out["is_weekend"] = (
            out["issue_reported_at"].dt.dayofweek.isin([5, 6]).astype(float)
        )
        out["issue_hour_sin"] = np.sin(2 * np.pi * hour / 24)
        out["issue_hour_cos"] = np.cos(2 * np.pi * hour / 24)
        out["issue_hour_bucket"] = pd.cut(
            hour,
            bins=[-1, 5, 11, 17, 21, 23],
            labels=[
                "Late Night",
                "Morning",
                "Afternoon",
                "Evening",
                "Night",
            ],
        ).astype("object")

    if "customer_remarks" in out.columns:
        remarks = out["customer_remarks"].fillna("").astype(str)
        out["remarks_length"] = remarks.str.len()
        out["remarks_word_count"] = remarks.str.split().str.len()
        out["has_customer_remarks"] = (
            remarks.str.strip().ne("").astype(float)
        )

    sparse_business_cols = [
        "item_price",
        "connected_handling_time",
        "customer_city",
        "product_category",
        "order_date_time",
        "customer_remarks",
    ]
    for col in sparse_business_cols:
        if col in out.columns:
            out[f"{col}_missing"] = out[col].isna().astype(float)

    for col in [
        "item_price",
        "connected_handling_time",
        "response_time_minutes",
        "order_to_issue_hours",
        "survey_delay_hours",
        "remarks_length",
        "remarks_word_count",
    ]:
        if col in out.columns:
            out[f"{col}_log1p"] = safe_log1p(out[col])

    return out


# -----------------------------------------------------------------------------
# Read categorical choices from the fitted encoder
# -----------------------------------------------------------------------------
def _clean_category_value(value):
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except Exception:
        pass
    return str(value)


def extract_training_options():
    options = {}

    cat_pipeline = preprocessor.named_transformers_["cat"]
    onehot = cat_pipeline.named_steps["onehot"]

    for index, feature in enumerate(CATEGORICAL_FEATURES):
        values = [
            _clean_category_value(v)
            for v in onehot.categories_[index]
        ]
        values = [
            v for v in values
            if v is not None and v.strip() != ""
        ]
        options[feature] = sorted(set(values), key=str.casefold)

    return options


TRAINING_OPTIONS = extract_training_options()

# Root choices are tightened using source-dataset relationships.
TRAINING_OPTIONS["category"] = sorted(
    UI_CONSTRAINTS["category_to_subcategories"].keys(),
    key=str.casefold,
)
TRAINING_OPTIONS["manager"] = sorted(
    UI_CONSTRAINTS["manager_to_supervisors"].keys(),
    key=str.casefold,
)


# -----------------------------------------------------------------------------
# Raw input parsing / validation
# -----------------------------------------------------------------------------
RAW_INPUT_FIELDS = [
    "channel_name",
    "category",
    "sub_category",
    "customer_remarks",
    "order_date_time",
    "issue_reported_at",
    "issue_responded",
    "survey_response_date",
    "customer_city",
    "product_category",
    "item_price",
    "connected_handling_time",
    "agent_name",
    "supervisor",
    "manager",
    "tenure_bucket",
    "agent_shift",
]


def blank_to_nan(value):
    if value is None:
        return np.nan
    if isinstance(value, str) and value.strip() == "":
        return np.nan
    return value


def has_value(value):
    if value is None:
        return False
    try:
        if pd.isna(value):
            return False
    except Exception:
        pass
    return str(value).strip() != ""


def compound_key(*values):
    return SEP.join(str(v) for v in values)


def validate_remarks(value):
    """
    Optional remarks may be blank.
    If supplied, require at least one letter or digit so punctuation-only
    values such as '.', '-', '...' are not treated as meaningful remarks.
    """
    if not has_value(value):
        return

    text = str(value).strip()
    if not re.search(r"[A-Za-z0-9]", text):
        raise ValueError(
            "Customer remarks contains only punctuation/symbols. "
            "Leave it blank or enter a meaningful remark."
        )


def validate_training_combinations(row):
    errors = []

    category = row.get("category")
    sub_category = row.get("sub_category")

    if has_value(category) and has_value(sub_category):
        valid_subs = UI_CONSTRAINTS[
            "category_to_subcategories"
        ].get(str(category), [])

        if str(sub_category) not in valid_subs:
            errors.append(
                f"Sub-category '{sub_category}' was not observed under "
                f"Category '{category}' in the training data."
            )

    manager = row.get("manager")
    supervisor = row.get("supervisor")
    agent = row.get("agent_name")
    tenure = row.get("tenure_bucket")
    shift = row.get("agent_shift")

    if has_value(manager) and has_value(supervisor):
        valid_supervisors = UI_CONSTRAINTS[
            "manager_to_supervisors"
        ].get(str(manager), [])

        if str(supervisor) not in valid_supervisors:
            errors.append(
                f"Supervisor '{supervisor}' was not observed under "
                f"Manager '{manager}'."
            )

    if has_value(manager) and has_value(supervisor) and has_value(agent):
        key = compound_key(manager, supervisor)

        valid_agents = UI_CONSTRAINTS[
            "manager_supervisor_to_agents"
        ].get(key, [])

        if str(agent) not in valid_agents:
            errors.append(
                f"Agent '{agent}' was not observed under the selected "
                "Manager/Supervisor combination."
            )

    if (
        has_value(manager)
        and has_value(supervisor)
        and has_value(agent)
        and has_value(tenure)
    ):
        key = compound_key(manager, supervisor, agent)

        valid_tenure = UI_CONSTRAINTS[
            "manager_supervisor_agent_to_tenure"
        ].get(key, [])

        if str(tenure) not in valid_tenure:
            errors.append(
                f"Tenure bucket '{tenure}' was not observed for the "
                "selected agent hierarchy."
            )

    if (
        has_value(manager)
        and has_value(supervisor)
        and has_value(agent)
        and has_value(shift)
    ):
        key = compound_key(manager, supervisor, agent)

        valid_shift = UI_CONSTRAINTS[
            "manager_supervisor_agent_to_shift"
        ].get(key, [])

        if str(shift) not in valid_shift:
            errors.append(
                f"Agent shift '{shift}' was not observed for the selected "
                "agent hierarchy."
            )

    if errors:
        raise ValueError(" ".join(errors))


def form_to_raw_frame(form):
    row = {
        field: blank_to_nan(form.get(field))
        for field in RAW_INPUT_FIELDS
    }

    validate_remarks(row.get("customer_remarks"))
    validate_training_combinations(row)

    parsed = {}
    for field in [
        "order_date_time",
        "issue_reported_at",
        "issue_responded",
        "survey_response_date",
    ]:
        value = row[field]
        parsed[field] = (
            pd.NaT
            if not has_value(value)
            else pd.to_datetime(value, errors="coerce")
        )

    if (
        pd.notna(parsed["issue_reported_at"])
        and pd.notna(parsed["issue_responded"])
        and parsed["issue_responded"] < parsed["issue_reported_at"]
    ):
        raise ValueError(
            "Issue responded time cannot be earlier than issue reported time."
        )

    if (
        pd.notna(parsed["order_date_time"])
        and pd.notna(parsed["issue_reported_at"])
        and parsed["issue_reported_at"] < parsed["order_date_time"]
    ):
        raise ValueError(
            "Issue reported time cannot be earlier than order time."
        )

    if (
        pd.notna(parsed["issue_responded"])
        and pd.notna(parsed["survey_response_date"])
        and parsed["survey_response_date"] < parsed["issue_responded"]
    ):
        raise ValueError(
            "Survey response time cannot be earlier than issue responded time."
        )

    return pd.DataFrame([row], columns=RAW_INPUT_FIELDS)


# -----------------------------------------------------------------------------
# Human-readable derived feature preview
# -----------------------------------------------------------------------------
def _fmt_number(value, decimals=1):
    if value is None:
        return "Not available"

    try:
        if pd.isna(value):
            return "Not available"
    except Exception:
        pass

    value = float(value)

    if abs(value - round(value)) < 1e-9:
        return f"{int(round(value)):,}"

    return f"{value:,.{decimals}f}"


def build_derived_preview(feature_frame):
    row = feature_frame.iloc[0]

    return {
        "response_time_minutes": (
            _fmt_number(row.get("response_time_minutes"))
        ),
        "order_to_issue_hours": (
            _fmt_number(row.get("order_to_issue_hours"))
        ),
        "survey_delay_hours": (
            _fmt_number(row.get("survey_delay_hours"))
        ),
        "issue_day_name": (
            "Not available"
            if pd.isna(row.get("issue_day_name"))
            else str(row.get("issue_day_name"))
        ),
        "issue_hour_bucket": (
            "Not available"
            if pd.isna(row.get("issue_hour_bucket"))
            else str(row.get("issue_hour_bucket"))
        ),
        "remarks_word_count": (
            _fmt_number(row.get("remarks_word_count"))
        ),
    }


# -----------------------------------------------------------------------------
# Prediction
# -----------------------------------------------------------------------------
def predict_csat(raw_frame):
    feature_frame = build_features(raw_frame)
    derived_preview = build_derived_preview(feature_frame)

    for feature in MODEL_FEATURES:
        if feature not in feature_frame.columns:
            feature_frame[feature] = np.nan

    model_input = feature_frame[MODEL_FEATURES]
    processed = preprocessor.transform(model_input).astype(np.float32)

    raw_probs = model.predict(processed, verbose=0)[0].astype(float)

    divisor = np.asarray(
        decision_config.get(
            "probability_divisor",
            np.ones_like(raw_probs, dtype=float).tolist(),
        ),
        dtype=float,
    )

    if divisor.shape != raw_probs.shape:
        raise ValueError(
            "decision_config probability_divisor does not match "
            "the ANN output."
        )

    safe_divisor = np.where(divisor <= 0, 1.0, divisor)
    adjusted_probs = raw_probs / safe_divisor

    total = adjusted_probs.sum()
    if total > 0:
        adjusted_probs /= total

    predicted_index = int(np.argmax(adjusted_probs))
    predicted_score = int(
        label_encoder.inverse_transform([predicted_index])[0]
    )

    probabilities = [
        {
            "score": int(score),
            "probability": float(adjusted_probs[i]),
        }
        for i, score in enumerate(label_encoder.classes_)
    ]

    return {
        "predicted_score": predicted_score,
        "model_probability": float(adjusted_probs[predicted_index]),
        "probabilities": probabilities,
        "model_name": MODEL_NAME,
        "derived": derived_preview,
    }


# -----------------------------------------------------------------------------
# Routes
# -----------------------------------------------------------------------------
@app.route("/", methods=["GET", "POST"])
def index():
    result = None
    error = None
    submitted = {}

    if request.method == "POST":
        submitted = request.form.to_dict()

        try:
            raw_frame = form_to_raw_frame(request.form)
            result = predict_csat(raw_frame)
        except Exception as exc:
            error = str(exc)

    return render_template(
        "index.html",
        result=result,
        error=error,
        submitted=submitted,
        training_options=TRAINING_OPTIONS,
        constraints=UI_CONSTRAINTS,
        model_name=MODEL_NAME,
        metrics=deployment_metrics,
        constraint_source=UI_CONSTRAINTS.get(
            "source_dataset",
            "training dataset",
        ),
    )


@app.route("/health")
def health():
    return {
        "status": "ok",
        "model": MODEL_NAME,
        "artifacts": "loaded",
        "ui_constraints": "loaded",
        "test_accuracy": deployment_metrics["test_accuracy"],
        "majority_baseline_accuracy":
            deployment_metrics["majority_baseline_accuracy"],
    }


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
